pretrain_data_dir: datasets/pretrain_data/train_questions
pretrain_dev_data_dir: datasets/pretrain_data/dev_questions
wikitables: datasets/tables.json
filtered_tables: datasets/preprocessed/tables_filtered.txt
pretrain_data: datasets/preprocessed/train.txt
pretrain_dev_data: datasets/preprocessed/dev.txt
random_neg_ratio: 1
hard_neg_ratio: 1
sample_hard_pretrain: False
execute_greedily: True
batch_size: 4
log_dir: logs
model_name: synthetic_pretrained
base_model: google/tapas-base
base_question_encoder: bert-base-uncased
base_tokenizer: google/tapas-base
model_dir: saved_models
learning_rate: 0.00005
num_epochs: 2